sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "mvn deploy"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - papokk@gmail.com
    on_success: change
    on_failure: always
